volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mariiavi/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: mariiavi/kittygram_frontend:latest
    volumes:
      - static:/static

  gateway:
    image: mariiavi/kittygram_gateway:latest
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
